# Stage 1: Obtener Docker CLI desde la imagen oficial
FROM docker:25-cli AS docker-source

# Stage 2: n8n con Docker CLI copiado
FROM docker.n8n.io/n8nio/n8n

USER root

# 1. Copiar el binario de docker (Lo que ya tenías)
COPY --from=docker-source /usr/local/bin/docker /usr/local/bin/docker
RUN chmod +x /usr/local/bin/docker

RUN npm install -g ldapjs

# Volver al usuario seguro
USER node