[databases]
; Bases de datos disponibles en 10.50.7.4
; Autenticación vía certificado mTLS (sin contraseña)
DB_QPREX      = host=10.50.7.4 port=5432 dbname=DB_QPREX      user=admin
DW_QPREX      = host=10.50.7.4 port=5432 dbname=DW_QPREX      user=admin
SERV_QPREX    = host=10.50.7.4 port=5432 dbname=SERV_QPREX    user=admin
DB_QPREX_TEST = host=10.50.7.4 port=5432 dbname=DB_QPREX_TEST user=admin
DW_QPREX_TEST = host=10.50.7.4 port=5432 dbname=DW_QPREX_TEST user=admin

[pgbouncer]
listen_port = 5432
listen_addr = *

; Autenticación de clientes que se conectan a pgbouncer
auth_type = trust
auth_file = /etc/pgbouncer/userlist.txt

; mTLS hacia el servidor externo en 10.50.7.4
server_tls_sslmode    = verify-ca
server_tls_ca_file    = /certs/ca-cert.pem
server_tls_cert_file  = /certs/admin-cert.pem
server_tls_key_file   = /certs/admin-key.pk8

; Pool
pool_mode         = transaction
max_client_conn   = 100
default_pool_size = 20

; Logs
log_connections    = 1
log_disconnections = 1
